### ISSUE TITLE
klipse freezes during code editing!

### ISSUE THREAD

**Issue by jiangts** [viebel/klipse#100]
I was trying to test the following code snippet on klipse `(range -10 10)`.
However, when typing up to `(range)` the whole page freezes!

**Comment by viebel** [comment]
This is because the code is evaluated as you type, with a delay of 20 msec
of inactivity. And `(range)` is an infinite list.

You can modify the delay, as explained in the README

**Comment by qgustavor** [comment]
For me it's still a bug: you can move evaluating to a WebWorker to fix this. They are [well supported](http://caniuse.com/#feat=webworkers).

**Comment by darwin** [comment]
I'm strongly  cannot move evaluating to a WebWorker to fix this. And definitely not easily.

**Comment by viebel** [comment]
This specific issue is fixed now.
Please check again

**Comment by qgustavor** [comment]
Understood... then I suppose my computer is too slow for this script.

**Comment by viebel** [comment]
@qgustavor @jiangts @darwin I solved the `(range)` issue by limiting the length of the strings emitted by the evaluation function. See https://github.com/viebel/klipse/blob/9591f12f9d674b842dc973a5587ca543db684e29/src/klipse/compiler.cljs#L46-L52
