### ISSUE TITLE
attaching  output (DOM fragments/ SVG) to current DOM from Klipse ?

### ISSUE THREAD

**Issue by bhugueney** [viebel/klipse#111]
I think that it would be awesome if it was possible for some Klipse snippets that return DOM fragments / SVG to have the result not displayed as text in a console output, but attached to the current DOM (the root could be a parameter ?).
It would allow to have interactive graphic code with Klipse, a nice thing imo.

Best Regards !

**Comment by viebel** [comment]
Sounds like a good idea. But I need more details: Can you share an example of use case?

**Comment by bhugueney** [comment]
My primary interest is in teaching programming and I think Klipse would be great to remove any barrier to entry in editing code to see the result. I would like to use generative programming as a relevant an engaging way to explain coding. What if the snippets from [this page](https://medium.com/@thi.ng/workshop-report-generative-design-with-clojure-7d6d8ea9a6e8#.yjjvelqdh) where editable Klipse fragments ?

Also, with the right libs, it would probably possible to have charts. Maybe a kind of client-side Clojurescript [gorilla repl](http://gorilla-repl.org/) would become possible ? (would be nice to store the edited code from Klipse in localstorage, now I'm getting carried away ☺).

**Comment by viebel** [comment]
For the first thing, it's kind of already possible today, using:   `editor_type: 'html'` in the `klipse_settings`:

Take a look at this demo: http://viebel.github.io/klipse/examples/markdown.html

For the second thing, I have a demo of using `nvd3`: http://blog.klipse.tech/javascript/2016/06/19/nvd3-demo.html

**Comment by viebel** [comment]
@bhugueney does it address your needs?
