### ISSUE TITLE
Usable from reveal.js (and org-reveal) presentations ?

### ISSUE THREAD

**Issue by bhugueney** [viebel/klipse#112]
I think it would be great to have Klipse snippets in presentations. [Reveal.js](https://github.com/hakimel/reveal.js/) is a pretty popular way to make online presentations, and I use it from emacs org mode thanks to [org-reveal](https://github.com/yjwen/org-reveal) that let me add raw HTML.

I tried [some simple test](https://gist.githubusercontent.com/bhugueney/b27879cd1c12125acfa4750320fbd0c7/raw/084ece1d967aff9a30d27bc1c8d00780d379d87a/Test-org-reveal-Klipse.org) but [the result](http://isep-ing-logiciel.github.io/II.3516/Test-org-reveal-Klipse.html) is unconvincing (watch out for httpS automatic redirect, one must use the http because of the reveal.js http source).

A way to embed Klipse in reveal.js presentations would be great !

Best Regards.

**Comment by viebel** [comment]
Reveal.js CSS interferes with CodeMirror CSS. There is an issue about it: https://github.com/codemirror/CodeMirror/issues/4189.

If you can solve this issue, it would be great.

Meanwhile, I am using deck.js: Here is a template for deck.js + KLIPSE: http://slides.klipse.tech/templates/deckjs/
