### ISSUE TITLE
data-external-libs could use an example in the README

### ISSUE THREAD

**Issue by diminishedprime** [viebel/klipse#116]
The is currently a reference to a site that used ```data-external-libs```, but by the time you inspect the html on that page, the div that had the ```data-external-libs=""``` has already been replaced by CodeMirror. It would be nice to have a simple example showing what the html element should look like.

```
<div class="klipse code-block" data-external-libs="https://raw.githubusercontent.com/diminishedprime/anagrams/master/src/">
    (ns your-namespace
    (:require [anagrams.core :as anagrams]))
</div>
```

**Comment by viebel** [comment]
You can take a look at the source page.
