### ISSUE TITLE
oCaml support for klipse

### ISSUE THREAD

**Issue by dvberkel** [viebel/klipse#148]
With this issue I would like to gauge the interest to support oCaml in klipse.

[BuckleScript](https://bloomberg.github.io/bucklescript/) is an excellent oCaml to JavaScript compiler, that also runs in [the browser](http://bloomberg.github.io/bucklescript/js-demo/#Tail_Call).

If there is interest, I am willing and hopefully able to provide a pull request integrating oCaml in klipse

**Comment by viebel** [comment]
That's exciting. I'm very very interested by being able to evaluate oCaml in klipse.
Then we would be able to write an interactive version of [the article behind core.match](http://www.cs.tufts.edu/~nr/cs257/archive/luc-maranget/jun08.pdf).

**Comment by dvberkel** [comment]
Great!

I will take some time to familiarize myself with BuckleScript and then try to include it in klipse.

**Comment by viebel** [comment]
You can take a look at how it is done for ruby  in this file
https://github.com/viebel/klipse/blob/master/src/klipse/lang/ruby.cljs
or python here
https://github.com/viebel/klipse/blob/master/src/klipse/lang/python.cljs

**Comment by dvberkel** [comment]
As detailed by @bobzhang in [ocsigen/js_of_ocaml/#528](https://github.com/ocsigen/js_of_ocaml/issues/528), the BuckleScript playground compiles and evaluates oCaml as expanded upon in [bloomberg/bucklescript#629](https://github.com/bloomberg/bucklescript/issues/629). At the moment there is no public exposed API but as can be seen [bloomberg/bucklscript#125](https://github.com/bloomberg/bucklescript/issues/125). 

Building upon these thoughts, a prototype of what we want can be seen is at [jsbin](https://dvberkel.jsbin.com/nihayux/edit?html,js,output). At the moment it only compiles the oCaml code. The JavaScript is not evaluated.

I will keep working on it until I have a single full round trip.

**Comment by viebel** [comment]
@dvberkel The prototype in jsbin doesn't work for me because files hosted on github ares served as text file. You have to host the file in another place.

**Comment by dvberkel** [comment]
@viebel I can't seem to loose the failing demos ;-)

I will keep working on it and convert the prototype to something that I have more control over.

**Comment by viebel** [comment]
@dvberkel any progress/blockers?
Do you need help?

**Comment by dvberkel** [comment]
I have made a (hopefully) working [prototype](https://dvberkel.github.io/klipse-ocaml-demo/).

The only problem that I have is doing to many things at once :-). I will probably work on integrating this with klipse tomorrow. If I get stuck, I will start asking questions.

**Comment by viebel** [comment]
Very nice! It should be straitforward to add ocaml into klipse.
Look for instance at [JSX integration into klipse](https://github.com/viebel/klipse/blob/master/src/klipse/lang/jsx.cljs) and grep for `klipse.lang.jsx`

**Comment by viebel** [comment]
I've create a first draft wiki page for instructions about how to add a new language in klipse https://github.com/viebel/klipse/wiki/How-to-add-a-language-to-klipse
