### ISSUE TITLE
render HTML

### ISSUE THREAD

**Issue by titaniumbones** [viebel/klipse#153]
How hard would it be to get klipse to render html?

**Comment by titaniumbones** [comment]
(that is, essentially build an html repl).

**Comment by viebel** [comment]
Its already there. Look at
https://github.com/viebel/klipse/blob/master/resources/public/plugin-dev.html

selector_eval_html is your friend

What is your use case?

**Comment by titaniumbones** [comment]
HTML tutorials.  Currently trying to export from org-mode using org-reveal.  Should the html code be escaped? Can it be in a <code> tag?

SO, e.g., will this work?
<pre><code class="html">
<h1>hi</h1>
</code>
</pre>

I would like to have live evaluation of html (with css support preferably) but need to figure out how to pass the code into the editor properly.

**Comment by viebel** [comment]
You need to escape `<` into `&lt;` and `>` into `&gt;` but if you are using
a markdown editor, it should escape it automatically for you

**Comment by titaniumbones** [comment]
It looks like I'm having some toruble getting code to escape properly. Not sure of hte solution...

**Comment by viebel** [comment]
Take a look here - https://github.com/viebel/klipse/blob/master/resources/public/plugin-dev.html#L452-L454
can you share your html page?

**Comment by titaniumbones** [comment]
It has something to do with the constraints of the iframe srcdoc attribute, maybe.  Here is a minimal broken example:
```html
<iframe srcdoc='<pre><code class= "klipse" data-editor-type="html" >
    &lt;h1&gt;hello&lt;/h1&gt;

</code></pre>
<link rel= "stylesheet" type= "text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">
<style>
  .CodeMirror { font-size: 2em; }
</style>
<script>
  window.klipse_settings = { selector_eval_html: ".klipse" };
</script>
<script src= "https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js"></script>'>
</iframe>
```
If you take away the iframe it works fine.

**Comment by titaniumbones** [comment]
ah wait, looks like maybe the & also needs to be escaped (this is like regexp in emacs!).  SO, this works:
```html
<iframe srcdoc="<html><body><pre><code class= &quot;klipse&quot; data-editor-type=&quot;html&quot; >
    &amp;lt;h1&amp;gt;hello&amp;lt;/h1&amp;gt; <>

</code></pre>
<link rel= &quot;stylesheet&quot; type= &quot;text/css&quot; href=&quot;https://storage.googleapis.com/app.klipse.tech/css/codemirror.css&quot;>
<style>
  .CodeMirror { font-size: 2em; }
</style>
<script>
  window.klipse_settings = { selector_eval_html: &quot;.klipse&quot; };
</script>
<script src= &quot;https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js&quot;></script></body></html>">
  
</iframe>
```

**Comment by viebel** [comment]
I think the reason is because in your case - using `srcdoc` -  the tags are part of a string.

So, everything works fine now?

**Comment by titaniumbones** [comment]
I guess.  It is pretty baroque though, and the emacs-lisp code that does the escaping seems unlikely to be accepted  the  unlikely to be accepted upstream. It looks like this:
```lisp
(if (string= lang "html" ) (replace-regexp-in-string "'" "&#39;"
                                                       (replace-regexp-in-string ">" "&amp;gt;"
                                                                                 (replace-regexp-in-string "<" "&amp;lt;" (car (org-export-unravel-code src-block)))))
    code)
```
 Would be better if reveal.js didn't cause so many errors, and we could just skip the whole iframe solution! I'd like to try to debug reveal, but I don't think that I have the skills.

**Comment by viebel** [comment]
Another option would be to embed klipse snippets into web components with
shadow DOM; then the css is isolated.

Would you like to take a look at this option?

**Comment by titaniumbones** [comment]
Yehonathan Sharvit writes:

> Another option would be to embed klipse snippets into web components with
> shadow DOM; then the css is isolated.
>
> Would you like to take a look at this option?
>
If I understood it better I would like to do so -- it seems intriguing.  I have managed a solution now for Emacs (https://github.com/titaniumbones/org-reveal/tree/klipse-support, seems to work for me), so the need is not pressing for me.  That said, I think it would be more elegant to implement the solution entirely in javascript and have it be a feature that can be turned on with window.klipse_settings at initialization.  This would require very little of third-party apps using the library, which I think would enhance compatibility with other tools.  

I myself am probably to going to be able to do this, though, so it would only make sense if you feel like it's at least somewhat worth your efforts.
