### ISSUE TITLE
klipse_settings keys for other languages are missing from the readme

### ISSUE THREAD

**Issue by alanbernstein** [viebel/klipse#158]
I just went to http://blog.klipse.tech/klipse/2016/09/09/klipse-languages.html and found what I needed - but it would be nice if the keys for other languages were listed in the readme, particularly `selector_eval_python_client` since it has that extra suffix.

**Comment by viebel** [comment]
a PR is welcome.

What is your use case with python @alanbernstein ?

**Comment by alanbernstein** [comment]
I was thinking about incorporating it into blog posts - I'd need to start making blog posts first...

**Comment by viebel** [comment]
What platform are you going to use for your blog?

**Comment by alanbernstein** [comment]
I would like to set up some silly custom system where org-mode files are automatically exported to html, then mirrored on my site. If I were to give up on that idea, then I would go with something with minimal effort, but I haven't looked into what that would be.

**Comment by viebel** [comment]
Oh! That's amazing...
[Matt Price](https://github.com/titaniumbones) is currently working on an integration of klipse into orgmode and org-reveal.
If you send me an email, I can add you to the thread on this topic.

**Comment by viebel** [comment]
Any progress on your blog?

**Comment by alanbernstein** [comment]
Not much - it's sort of low priority at the moment.
