### ISSUE TITLE
Cursor rendering issue

### ISSUE THREAD

**Issue by davezuko** [viebel/klipse#164]
Hey, awesome tool! I'm trying to use this for some online code documentation, but there seems to be an issue with how the cursor renders. I have reproduced this in latest Chrome, Safari, and Firefox, and then, thinking it may be an issue with my template, copied the demo from https://jsfiddle.net/viebel/50oLnykk/ and ran it locally and the same issues occur.

Not sure if this is a browser quirk or something with klipse, but hopefully you can help me narrow this down. For some reason, the demo seems to work just fine in the jsfiddle, but I can't figure out for the life of me what could possibly be different. Note that there are not any additional stylesheets at play, just purely the css recommended by klipse.

<img width="1052" alt="screen shot 2016-12-22 at 7 38 55 am" src="https://cloud.githubusercontent.com/assets/6439050/21427488/82b1acf4-c81a-11e6-937f-f99c771f4c8e.png">

<img width="902" alt="screen shot 2016-12-22 at 7 38 08 am" src="https://cloud.githubusercontent.com/assets/6439050/21427486/813a6726-c81a-11e6-8e0b-b78c2c7cd0ef.png">

Here is the minimal code that reproduces this issue locally:

```html
<!doctype html>
<html>
<body>
<div class="klipse">
 function foo(name) {
 return "Hello " + name;
 }
 foo("Klipse");
</div>
<link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css">
<script>
    window.klipse_settings = {
        selector_eval_js: '.klipse', // css selector for the html elements you want to klipsify
    };
</script>
<script src="https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js"></script>
</body>
</html>
```

Thank you for your help!

**Comment by viebel** [comment]
It took me a while to discover that you have to add this line into the `<head>` part of the html:

```html
    <meta charset="utf-8">
```

The reason it works fine on jsfiddle is that when the html file is served by a server, the charset is automatically `utf-8`.

1. Please confirm that it works on your side
2. What online code documentation do you want to have?

**Comment by davezuko** [comment]
That did the trick, thank you for digging into it and managing to figure that out, I'm not sure I would have ever figured that one out. This was just a quick template I threw together the other day, so any other site would have had that tag but it just so happened that I'd forgotten it when scaffolding the docs. Also appreciate the addition to https://github.com/viebel/klipse#integration, hopefully that helps others.

The docs are for a library I'm working on; it's in incredibly rough shape right now, but I needed to get something out for some friends who are trying it out. You can check it out (along with your awesome Klipse integration) here: https://redash.zuko.me/.

**Comment by viebel** [comment]
Oh it's a functional programming lib on javascript. right?

1. Where is the github repo?
2. You should make a generic tool for javascript interactive repo. What do
u say?

**Comment by davezuko** [comment]
@viebel, here is the repo: https://github.com/davezuko/redash. As far as #2, I would definitely love to do that, but am not sure I have enough time in the day. Maybe I'll start something eventually :).

Have a merry Christmas!
