### ISSUE TITLE
integrate klipse with React

### ISSUE THREAD

**Issue by IanWang** [viebel/klipse#183]
Firstly, awesome project, thank you for the great work!

I was trying to integrate klipse with react components, but it doesn't seem to work
http://jsbin.com/kobahoquvu/edit?html,js,output 

Did I miss something? or is there a way that I can manually restart the klipse?

**Comment by viebel** [comment]
Thanks @IanWang 
The reason is that klipse is loaded before react has added it's element to the dom. There are 2 solutions:
1. delay a bit the loading the klipse script
2. after react is loaded, run `klipse.plugin.init(klipse.run.plugin_prod.plugin.settings());` - it will make klipse reparse the DOM and convert the selected elements to klipse snippets.

BTW, what do you plan to do with the integration of klipse with react?

**Comment by viebel** [comment]
This is the modified `jsbin`s that demonstrate it:

1. delay a bit the loading the klipse script - http://jsbin.com/nuhusu/edit?html,js,output
2. after react is loaded, run `klipse.plugin.init(klipse.run.plugin_prod.plugin.settings()); ` - http://jsbin.com/conobo/edit?html,js,console,output

**Comment by IanWang** [comment]
oh nice! Thanks for helping. I think I'll go for 2). 

I'm working on a new project at Codementor which involves a markdown editor that can generate klipse snippets in preview mode. Should be available in a couple of weeks. We're trying to build a knowledge sharing network for our community, so the editor is also one of the crucial parts of it.
 
Would love to give you an update when it's online. 😄

**Comment by viebel** [comment]
@IanWang have you made progress on your project?

**Comment by IanWang** [comment]
yes! it works well and really brings post like tutorial to another level!
We haven't released it yet since there might be some XSS concern.
[here](https://www.codementor.io/write-on-codementor) is the early version of the editor

**Comment by viebel** [comment]
@IanWang 
CodeMentor looks really great.
I'm working on supplying a setting in klipse that will make the execution of the snippets into a sandbox with limited access to the window object: no access to `document` (cookies), no access to ajax functions.

I'd be happy to open a Clojure community on CodeMentor.

Maybe we can continue this conversation on email: viebel@gmail.com

**Comment by viebel** [comment]
@IanWang there is now a [secured mode](http://blog.klipse.tech/klipse/2017/03/14/secured-eval.html) inside KLIPSE that prevents malicious code and XSS.

**Comment by IanWang** [comment]
Wow it's awesome! Thank you @viebel!
I don't have any examples right now since the feature is not really available
but with `secured_eval`, I believe I can make it public very soon
I was thinking to *upgrade* posts like these:
- [Computer Algorithms Explained](https://www.codementor.io/mattgoldspink/computer-algorithms-explained-learning-through-spotify-du10866vw)
- [The Ultimate JavaScript Cheat Sheet](https://www.codementor.io/johnnyb/javascript-cheatsheet-fb54lz08k)

**Comment by viebel** [comment]
Both articles are very good candidates for being klipsified: one is very
basic and one is for experienced js developpers.

Let me know if you need any kind of help with the integration of Klipse.

**Comment by viebel** [comment]
@IanWang Please wait a bit before allowing people to write interactive content - as there are still flaws in Klipse secured mode.

**Comment by IanWang** [comment]
👌
