### ISSUE TITLE
Feature request: Support HTML as a language

### ISSUE THREAD

**Issue by timothypratley** [viebel/klipse#185]
It would be great to be able to show life HTML snippets :)

Example:

```
<pre><code class="klipse-html">
&lt;h1&gt;Hi&lt;/h1&gt;
</code></pre>
```

Should render:

```
<h1>Hi</h1>
```

Then if the user changes the box to Hello, it updates :)

**Comment by viebel** [comment]
Actually, it's already possible.
Have a look here: http://read.klipse.tech/p/68026e45-45ad-413d-9e38-d169b3df5805/
