### ISSUE TITLE
[python] find a way to share functions between snippets

### ISSUE THREAD

**Issue by viebel** [viebel/klipse#199]

**Comment by Naereen** [comment]
Hi @viebel.
First, congrats and bravo and thanks for this nice project :clap: !
I was going to ask a similar question, about OCaml.

I had in mind to write a custom converter for Jupyter notebooks that will convert to a static HTML file using Klipse to evaluate cells, but the main problem would be that such page would be useless for almost any real case of notebooks: content of previous cells are used in next cells...

Is there any update on this?

**Comment by viebel** [comment]
No. The issue is still here.

**Comment by Naereen** [comment]
Thanks for replying... I kept thinking about this, and I don't think it would be an easy task to implement this for all the languages supported by klipse...

**Comment by viebel** [comment]
In most langugages (e.g. Clojure, JavaScript, Ruby and mode), code is shared between snippets.

**Comment by vrthra** [comment]
So, it seems that sharing functions and objects works in the home page <http://skulpt.org/#>. If I import `sys` in the first code window, I can print `sys.version` in the second code window. So, my question is, how does it work? and how do we use this elsewhere?

**Comment by viebel** [comment]
Oh nice!
I don't know how it works on http://skulpt.org/#.
Could you ask on their support channel?

**Comment by vrthra** [comment]
Seems like the magic is `retainglobals: true` passed to `SK.configure`

**Comment by viebel** [comment]
@vrthra Working on integrating it into Klipse.

**Comment by viebel** [comment]
Fixed! @vrthra @Naereen .
