### ISSUE TITLE
Initialize a code block only after an event is triggered

### ISSUE THREAD

**Issue by settinghead** [viebel/klipse#210]
I am trying to use Klipse on a page that contains a lot of code blocks (https://clause.js.org). My problem is that the page is long and initial loading time is slow and the page freezes for up to 20 seconds on slower computers.

Is there any way that I can selectively target a few code blocks and load them *only* after an event is triggered? For example, only load a group of code blocks in a section after a button is clicked. Thanks!

**Comment by viebel** [comment]
First of all, `clausejs` looks awesome. Bringing the power of `clojure.spec` to javascript is a great idea. There is another project based on the same idea: https://github.com/prayerslayer/js.spec


You can achieve what you want like this:

1. Include in `klipse_settings.selector_eval_js` only the code blocks that you want to klipsify on page load
2. set `klipse_settings.selector_eval_js` to include the code blocks that you want to  klipsify later
3. call `klipse.plugin.init(klipse.run.plugin_prod.plugin.settings())`

Please let me know if it improves the perfs of page load.

**Comment by settinghead** [comment]
@viebel I followed your suggestios and it works great now. Initial page load time has been significantly reduced. Thanks for making this awesome plugin and keep up the good work!
