### ISSUE TITLE
Could klipse not download extra resources automatically ?

### ISSUE THREAD

**Issue by Lucas-C** [viebel/klipse#215]
When I use klipse_plugin v6.5.0, it tries to download the following files :

- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.21.0/mode/javascript/javascript.min.js
- https://viebel.github.io/klipse/repo/js/pretty_format.js

This blocks me from working offline.

Could you distribute klipse as a self-sufficient bundle ?

**Comment by viebel** [comment]
The codemirror root and the scripts root are configurable in the `klipse_settings`:

```
codemirror_root: '/my-codemirror-root', // the root of codemirror files
scripts_root: '/my-scripts-root', // the root of scripts files (e.g pretty_format.js, \
opal.js ...)
```

You can download `javascript/javascript.min.js` from `cdnjs` and `pretty_format.js` from `viebel.github.io` and configure `klipse_settings` accordingly.

Does it make sense?

**Comment by viebel** [comment]
I will probably need to add a word about it in the `README` (A PR is welcome) ...

**Comment by Lucas-C** [comment]
It makes complte sense, thanks.
Alas it also means that klipse cannot be used in a page served with the `file:///` protocol :
```
XMLHttpRequest cannot load file:///E:/Educ/AtelierProg_2016-10-08/workshop_material/libs/js/javascript/javascript.min.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

The `file://` protocol is very handy to avoid installing a file-serving server on students computers where sometimes you do not have admin access and/or there is strict software install policy (that happened to me).

**Comment by viebel** [comment]
I may have a solution: Could you to script tags for `javascript/javascript.min.js` and `pretty_format.js` (or bundle all the files in one)?

And then in an upcoming klipse version - I will provide a setting `no_dynamic_scripts` that makes sure no resource is loaded dynamically.

Will it work for you?

**Comment by Lucas-C** [comment]
Sorry, what do you mean by "Could you to script tags" ?

Anyway this is not urgent, I can wait for the next version

**Comment by viebel** [comment]
@Lucas-C  I mean: If I'm adding the `no_dynamic_scripts` option, Could you to add script tags to your page for `javascript/javascript.min.js` and `pretty_format.js` (or bundle all the files in one)?

I had a typo in my previous message.
Sorry for the confusion.

Does it make sense now?

**Comment by Lucas-C** [comment]
Sure ! Sounds good

**Comment by jdeisenberg** [comment]
I have tried setting both `codemirror_root` and `scripts_root`; setting `codemirror_root` to a directory on the local server (`dist/codemirror`) works. Setting `scripts_root` to `dist/docs/repo/js`, which does exist and is world-readable, does not work; the code is still looking for `https://viebel.github.io/klipse/repo/js/bs.js` This is with the minified plugin from a cloned version of the project.

**Comment by viebel** [comment]
@jdeisenberg can you try to add `klipse_settings.no_dynamic_scripts=true`?

**Comment by jdeisenberg** [comment]
That got rid of the error message, and now the only output in the “result” area is `Line :- `
I am running on a Raspberry Pi, if that makes a difference. Should I rebuild the minified plugin (and, if so, what are the build instructions)?

**Comment by jdeisenberg** [comment]
Note: I have a copy of the code that I am testing at http://langintro.com/reasonml/ktest.tgz, and the web page itself (unpacked from the tarfile) is at http://langintro.com/reasonml/ktest/

**Comment by jdeisenberg** [comment]
OK; I’m an idiot. Since the files from `repo/js` aren’t being fetched from the web, I have to manually load them myself.  I copied the `repo/js` directory and added this at the bottom of the web page, and it looks like it works great.

```
<script src="repo/js/bs.js"></script>
<script src="repo/js/refmt-3.js"></script>
<script src="repo/js/stdlibBundle.js"></script>
<script src="repo/js/pretty_format.js"></script>
<script src="dist/klipse_plugin.min.js"></script>
```

**Comment by viebel** [comment]
No problem @jdeisenberg

**Comment by fmitchell61** [comment]
Big Thank You to viebel for creating klipse.
And another Big Thank You for jdeisenberg for the _ktest.tgz_ file.
