### ISSUE TITLE
Newly opened articles scroll down

### ISSUE THREAD

**Issue by mgerlach-klick** [viebel/klipse#22]
I couldn't come up with a better title. Sorry.

When opening a new article on the Klipse blog the site starts out scrolled to the top, but the more content gets loaded in, the more the page scrolls down. On the defprotocol article for instance, a fully loaded page ends up opened 85% through (see attached screenshot).
![2016-04-10 at 3 02 pm](https://cloud.githubusercontent.com/assets/4621981/14412308/b60f4e14-ff2d-11e5-8bf1-019a2ed3059c.png)
This happens on both Safari / OS X.10.3 and on the latest Firefox (same OS)

**Comment by viebel** [comment]
The issue has been fixed.
No more iframes with the klipse plugin!
