### ISSUE TITLE
Messed up JavaScript object indentation

### ISSUE THREAD

**Issue by polytypic** [viebel/klipse#229]
The indentation of JavaScript objects in output is messed up.  Here is [an example](https://calmm-js.github.io/partial.lenses/#L-values):

<img width="914" alt="screen shot 2017-02-21 at 19 20 08" src="https://cloud.githubusercontent.com/assets/5804945/23176237/ee7b8cea-f86a-11e6-9db6-e00c2c569b73.png">

This started several versions ago and I can see this also on other sites that use KLIPSE.

**Comment by viebel** [comment]
Thanks for opening this issue. Will take a look at it soon

**Comment by viebel** [comment]
@polytypic Solved in klipse version 6.7.1 (deployed on Feb 23, 2017)

Please confirm that it works fine now.

**Comment by polytypic** [comment]
Seems to be fixed now.  Thanks!
