### ISSUE TITLE
Screenshot in contributing.md outdated

### ISSUE THREAD

**Issue by flyjwayur** [viebel/klipse#239]
![klipse- a simple and elegant online cljs compiler and evaluator clipular](https://cloud.githubusercontent.com/assets/11784820/23673439/fde9c7da-037a-11e7-889e-6c3e7ea6394d.png)

I took a new screenshot, but I don't know where is the best place to host this screenshot file. If using screenshot with above link is ok or if you could tell me where to host, I will make a pull request. But I assume that you would want to host the file under `http://blog.klipse.tech/assets`, as it currently is.

**Comment by viebel** [comment]
It's ok to host screenshots on github :)
