### ISSUE TITLE
`console.log` should return `undefined`

### ISSUE THREAD

**Issue by polytypic** [viebel/klipse#243]
The standard `console.log` of JavaScript returns `undefined` ([spec](https://console.spec.whatwg.org/#logger)).  KLIPSE (6.7.1) replaces the `console.log` operation with a function that returns `true`.  This can cause problems with JavaScript code.  It would be best to return `undefined` also from the `console.log` replacement that KLIPSE uses.

**Comment by viebel** [comment]
Solved in version 6.7.7
