### ISSUE TITLE
update documentation with new class names

### ISSUE THREAD

**Issue by webappzero** [viebel/klipse#244]
I had a hard time getting started with Klipse because the class names listed in the README and the Git Book are outdated. Our recent webinar video helped me correct the bad code.

I'll submit some PRs, but wasn't confident that I'm doing everything right.

Did these class names recently change from `'.language-klipse'` to just `.klipse` etc.?

**Comment by viebel** [comment]
The class names are completely arbitrary: you can chose `'.klipse'`, `'.my-klipse'`, `'.foo'` or whatever you decide.

The only issue is with markdown engine that modify the DOM elements with classes that are suppose to contain static code snippets like `.language-ruby` or `.lang-clojure`.

**Comment by webappzero** [comment]
So in my `<script>` element I have:

` <script>
    window.klipse_settings = {
        selector: '.clojure'
    }
 </script>`

And above that in my html file I have:

` <pre ><code class="clojure"> 
   (map inc [1 2 3])
 </code></pre>
`

Are you saying that the `.clojure` class is arbitrary, but it just has to match between where it is defined in the `window.klipse_settings` object and where it is used as the `class` attribute, as in the example above?

If so, that explains my confusion. Is that prominently explained somewhere? This wasn't obvious to me. Thank you.

**Comment by viebel** [comment]
You got it right Jay.
And it's not very clear from the README.
I'd appreciate if you can formulate it more clearly.

**Comment by webappzero** [comment]
I'd be happy to help with the wording used in the documentation. I'll touch base with some PRs or questions soon.
