### ISSUE TITLE
In javascript, function definitions should be shared between snippets

### ISSUE THREAD

**Issue by viebel** [viebel/klipse#246]
A function that is defined in a snippet is not always accessible to other snippets.

For instance, the following won't work:

```javascript
function foo() { return 1;}
```

```javascript
foo()
```

Workaround:

```javascript
foo = function() { return 1;}
```

```javascript
foo()
```

**Comment by polytypic** [comment]
My interactive partial.lenses documentation is now completely broken as are several other klipse based pages.

How do I refer to a specific version of klipse.  Currently I'm using the URI

  https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js

to load klipse.

Perhaps you could introduce a 6.7.8 version reverting the scoping changes in klipse and release a new major version.

**Comment by viebel** [comment]
Sorry about that @polytypic .
For the moment, there is no way to refer an earlier version of klipse.

I will do my best to fix it ASAP.

What is the link to you partial.lenses doc?

**Comment by viebel** [comment]
I think it's a regression introduced yesterday by the secured_mode.
Will deploy a fix soon.

**Comment by polytypic** [comment]
Here is the link:

  https://calmm-js.github.io/partial.lenses/

I set libraries to the window object after loading the bundle of libraries that the snippets use:

  https://github.com/calmm-js/partial.lenses/blob/master/docs/start.js#L6-L9

Those are no longer implicitly accessible in 6.7.8.

**Comment by viebel** [comment]
I have just deployed a fix: version `6.7.9`

Your interactive documentation looks OK.
Please confirm.

Also, I will provide a way to access older klipse versions.

**Comment by polytypic** [comment]
Thanks!  Seems to work now.

Being able to access old versions would be great.  I've had presentations with klipse snippets.  A breaking change just before presentation would be awkward and could be prevented/fixed by pinning to a(n older) working version.

**Comment by viebel** [comment]
From version 6.8.0 (today's version), you can use older Klipse version. See https://github.com/viebel/klipse/blob/master/README.md#use-older-versions
