### ISSUE TITLE
how to use data-external-libs in  gitbook

### ISSUE THREAD

**Issue by anandrikka** [viebel/klipse#249]
I have tried below code in one of my mark down file, but it's not working
"
```eval-js
<pre class="hidden"><code class="lang-eval-js" data-external-libs="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.min.js>
</code></pre>
ReactDOM.render(
<h1>Hello, World !!</h1>,
document.getElementById('root')
);
```
"

Let me know how to use plugin with react library in gitbook markdown files

**Comment by viebel** [comment]
You need to pass a comma separated list of js files to `data-external-libs`.

In your case:

data-external-libs="
https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom-server.min.js
, https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.min.js,
https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.min.js"

**Comment by anandrikka** [comment]
Thanks viebel, but I have already tried to place it in my .md file. It's not working. Could you please provide any code snippet. I'm using gitbook editor.

**Comment by viebel** [comment]
Oh. This is because you use `JSX`.
I have updated the [klipse gitbook](https://book.klipse.tech/interactive_javascript_code_snippets.html?saa) with the instrcutions for React and JSX. 

You might need to clean your browser cache to get the latest version of the gitbook.

Please confirm that it works now.

**Comment by anandrikka** [comment]
Thanks man,
Here's the final code
{
% raw %}
<pre class="hidden"><code class="lang-eval-js" data-external-libs="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-with-addons.js, https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js">
React
</code></pre>
{% endraw %}

```eval-jsx
ReactDOM.render(
<h1>Hello, World !!</h1>,
document.getElementById('container'));
```
{% raw %}
<div id="container"></div>
{% endraw %}

**Comment by viebel** [comment]
What are you building?

**Comment by anandrikka** [comment]
I'm writing a gitbook on ReactJs and wanted to provide interactive examples. I found your plugin great !!

**Comment by anandrikka** [comment]
Can you do one more help.

How do yo included babel transpiler in your JSX (react) in depth - an interactive tutorial

**Comment by viebel** [comment]
I have updated the Klipse gitbook with instructions about jsx transpilation.


A interactive gitbook about ReactJs sounds great!
Can you share a link to your work in progress (my email is: viebel@gmail.com)?

**Comment by viebel** [comment]
@anandrikka I have created a page for having react klipse snippet: https://book.klipse.tech/how-to-create-interactive-reactjs-snippets.html

Please take a look at the automatic rendering of JSX.

**Comment by anandrikka** [comment]
@viebel Thank you, this will help me a lot.
