### ISSUE TITLE
loading goog.string.format fails on blog page

### ISSUE THREAD

**Issue by daslu** [viebel/klipse#256]
At the [blog post about self-host namespace loading](http://blog.klipse.tech/klipse/2016/10/16/klipse-is-fast.html), the following errors appear the the console:

GET https://raw.githubusercontent.com/google/closure-library/v20160713/closure/goog/string/format.js 404 (Not Found)
GET https://raw.githubusercontent.com/google/closure-library/v20160713/closure/goog/string/format/format.js 404 (Not Found)

**Comment by viebel** [comment]
@daslu The errors are related to the fact that Klipse tries a couple of options for namespace resolution.
