### ISSUE TITLE
Provide tighter integration with Asciidoc

### ISSUE THREAD

**Issue by jocrau** [viebel/klipse#258]
Asciidoc is a way to write text documents in plain text that can be transformed into numerous different output formats (eg. using Asciidoctor). It also provides a semantical block for writing source codes snippets and apply syntax highlighting (http://asciidoctor.org/docs/user-manual/#source-code-blocks).  There are several syntax highlighters to choose from, which can be specified in the preamble of the document (CodeMirror is not one of them). Ideally, I would like to write something like:

```
:source-highlighter: klipse

[source,clojure]
----
(+ 1 2)
----
```
 
My current workaround looks like:

```
window.klipse_settings = {
    selector: '.eval-clojure pre'
}
```

in combination with

```
[.eval-clojure]
----
(+ 1 2)
----
```

This works fine, but has its limits. For example, it is not possible to add callouts to the snippet (described here: http://asciidoctor.org/docs/user-manual/#callouts). And it would be great to have the Klipse related JS code automatically inserted into the rendered HTML document (rather than using `docinfo-footer.html` file).

I am sure that the combination of Asciidoctor, Klipse (and [Reveal.js](https://github.com/hakimel/reveal.js/ ) for slides) is going to be killer application ;-) .

**Comment by viebel** [comment]
Thanks for this information and the suggestions @jocrau.

Could you show an example of an integration of Klipse and Reveal?

Last time I tried, I had a couple of CSS issues as described here: https://github.com/codemirror/CodeMirror/issues/4189#issuecomment-271863685

**Comment by jocrau** [comment]
I did not Klipse in combination with Reval.js in my presentation. But I tried to get it to work yesterday.

I ran into similar problems that you described in the referenced issue (cursor not visible), and experienced additional ones (code box collapsed to a slim line). I suspect those issues have todo with a CSS "positioning" setting. I will try to fix that later today or tomorrow.

**Comment by viebel** [comment]
That would be awesome if you fix the CSS issues @jocrau !!!

**Comment by viebel** [comment]
Were you able to solve (or maybe workaround?) the CSS issues between reveal and CSS?

**Comment by jocrau** [comment]
I have that still on my list. An upcoming presentation will put some pressure on this ... ;-)

**Comment by timothypratley** [comment]
To fix cursor not visible, add this CSS:
```
.CodeMirror-cursor {
  border-left: 1px solid black !important;
}
```

To fix code box collapsed to a slim line, add this JavaScript:
```
<script>
    Reveal.addEventListener( 'slidechanged', function() {
        window.dispatchEvent(new Event('resize'));
    } );
</script>
```

To fix strange cursor movement and highlighting, set these attributes in your .adoc file
```
:revealjs_minScale: 1.0
:revealjs_maxScale: 1.0
```
