### ISSUE TITLE
"reagent is not defined"

### ISSUE THREAD

**Issue by daslu** [viebel/klipse#265]
At the [reagent blog post](http://blog.klipse.tech/reagent/2016/12/31/reagent-in-klipse.html):

Currently the rendered reagent component shows the following error:
> #error {:message "ERROR", :data {:tag :cljs/analysis-error}, :cause #object[ReferenceError ReferenceError: reagent is not defined]}

and the browser console says:
> Failed to load resource: the server responded with a status of 503 (Backend is unhealthy)
> viebel.github.io/klipse/cache-cljs//reagent_SLASH_ratom$macros.js

**Comment by daslu** [comment]
Closing this, as it works again - thanks!

**Comment by viebel** [comment]
I should improve the error message

**Comment by viebel** [comment]
There were issues with github pages today.
