### ISSUE TITLE
klipse with markdown

### ISSUE THREAD

**Issue by lambda-knight** [viebel/klipse#279]
I am trying to integrate klipse with markdown.
The attached example doesn't work. If I could put the css to html head.

[test.md.txt](https://github.com/viebel/klipse/files/1272566/test.md.txt)

This is not klipse issue but is there any resolution ?

**Comment by viebel** [comment]
Can you please share the html that is generated from the markdown?

**Comment by lambda-knight** [comment]
I understood it depends on markdown processor.
I could generate a html which works on chrome using marked.
https://github.com/chjj/marked

The generated html is as follows:

```html
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<title>clojure-example.html</title>

</head>

<body>

<link rel="stylesheet" type="text/css" href="https://storage.googleapis.com/app.klipse.tech/css/codemirror.css" />

<h1 id="sample-clojure-code">sample Clojure code</h1>
<pre><code class="lang-clj">(map inc &#39;(1 2 3 4))
</code></pre>
<script type="text/javascript">window.klipse_settings = {selector: '.lang-clj'};</script>
<script src="https://storage.googleapis.com/app.klipse.tech/plugin/js/klipse_plugin.js"></script>


</body>
</html>
```

However, markdown-preview-plus doesn't.
https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl
