### ISSUE TITLE
Can it be embeded in medium

### ISSUE THREAD

**Issue by kennetpostigo** [viebel/klipse#283]
Really would love to use this in medium, like codepen/codesandbox, is this possible?

**Comment by viebel** [comment]
In theory, yes.
In practice, no.

To make the theory happen I would have to convince medium to integrate Klipse in their platform - as medium doesn't support arbitrary script tags.

But Klipse works fine with jekyll and ghost.

**Comment by idkjs** [comment]
Cant seem to embed in dev.to either. Do you know if its possible?

**Comment by viebel** [comment]
It has security issues as Klipse snippets run as part of the page not as iframe.

**Comment by idkjs** [comment]
I love this project. Keep trying to use it. Side note. Oddly, using the css tags in ReasonML projects doesnt seem to work. It just loads the text. If there is some obvious reason you are aware of that this doesn't work, please do share. Thanks for sharing your work, sir.
