### ISSUE TITLE
reason 3

### ISSUE THREAD

**Issue by kennetpostigo** [viebel/klipse#284]
Reason 3 was released about ~1 week ago, does klipse need to make any changes to support the new syntax?

**Comment by viebel** [comment]
We need to update the refmt.js script.
If you can put here a link to an updated self-contained `refmt.js` script I will handle it.

**Comment by kennetpostigo** [comment]
cc @chenglou

**Comment by chenglou** [comment]
It's now installable as a repo, `npm install --save reason`. Though I guess you'd still want to vendor it?

**Comment by viebel** [comment]
@kennetpostigo Klipse now supports Reason 3 See https://twitter.com/viebel/status/930853934247415811
