### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by myklam** [viebel/klipse#287]
I was wondering what is the best way to share code between different Klipse elements?

Currently, I have two different Klipse elements, and the second references an object created in the first. The code looks like this:
The first element:
```html
<div class="hidden klipse-eval-js">
  let me = { name: "mike", age: 25 };
</div>
```
The second element:
```html
<div class="klipse-eval-js">
  me.age;
</div>
```

I was hoping the output of the second element would just be ```25```, but instead I get the error pictured below:
<img width="632" alt="klipse-reference-error" src="https://user-images.githubusercontent.com/10170691/32691565-2a6e3d50-c6cf-11e7-9720-a2ad3dde4cdc.png">

If I remove the ```let``` from the declaration of ```me``` in the first element, everything works as expected.

So, my question is, is there something that I'm missing to be able to use ```let``` or ```const```, and then be able to reference those values in other Klipse elements? Or, do I simply have to declare the variables as globals to make them accessible in other elements?

I am hoping that I can use ```let``` or ```const``` so that I can maintain good coding practices in blog posts! Also, if it changes your answer at all, I'm using [hexo](https://hexo.io/) to generate the site, so I'm not sure if that could somehow be messing up the ability to share values between elements.

Let me know if there is anything more you need of me, or if there is anything I can do to help!

Thanks!

**Comment by viebel** [comment]
This is the way `eval` works in javascript.

You can workaround this behaviour by appending to the first code snippet this piece of code:
```javascript
window.me = me
```
