### ISSUE TITLE
ReasonML keyword "switch" syntax colored as cm-variable

### ISSUE THREAD

**Issue by jkleiser** [viebel/klipse#291]
In the "fact" (factorial) example, the words "let" and "rec" are correctly given span class "cm-keyword", but the "switch" word is given span class "cm-variable".
I'm using selector_eval_reason_3: '.language-klipse-reason'.

**Comment by viebel** [comment]
Klipse uses CodeMirror for formatting code snippets.
[CodeMirror](https://codemirror.net/mode/) doesn't have yet a ReasonML mode.
Klipse uses ocaml mode for ReasonML snippets.
