### ISSUE TITLE
put the codemirror components in div's  (allowing horizontal layout)

### ISSUE THREAD

**Issue by fredokun** [viebel/klipse#297]
It would be nice to allow other layouts than the current source/result vertical layout. In particular a horizontal layout in the spirit of the famous Brett Victor's _Inventing on Principle_ video (https://www.youtube.com/watch?v=PUv66718DII) would be nice.  @viebel told me it is mostly a matter of inserting div's as parent of the source and result codemirrors.

**Comment by viebel** [comment]
There is work in progress about it. See

**Comment by viebel** [comment]
Solved by #299.

Here is a demo of horizontal layout: http://viebel.github.io/klipse/examples/styling-snippet.html

I hope it fits your needs @fredokun

**Comment by fredokun** [comment]
this is perfect, thanks!
