### ISSUE TITLE
add libraries

### ISSUE THREAD

**Issue by lambda-knight** [viebel/klipse#303]
Can klipse add libraries for clojure and javascript ? If it possible, let me know how to do it.

**Comment by viebel** [comment]
For javascript libs, it's super simple: you add a `<script>` tag with a link to your favorite lib on npm cdn e.g. https://unpkg.com/#/ 
For clojure libs, some libs are already configured by Klipse like `clojure.set` so it will work out of the box with `(require 'clojure.set)`. For other libs, you need to provide `data-external-libs` to the dom element that contains the `require` statement as explained [here](https://github.com/viebel/klipse#clojure-only-1). See for instance this [page](https://github.com/viebel/klipse/blob/master/docs/examples/cuerdas.html).

**Comment by viebel** [comment]
@lambda-knight What is the address of your Klipse powered blog post?
