### ISSUE TITLE
Common Lisp's (loop) can hang the browser tab

### ISSUE THREAD

**Issue by svetlyak40wt** [viebel/klipse#309]
When you enter `(loop)` in the snippet, editor hangs and browser eats all CPU. You have no chance to add loop conditions.

Seems this issue is related to https://github.com/viebel/klipse/issues/308 (evaluation after each keystroke).

**Comment by viebel** [comment]
There are two issues here:

1. The user intentionally evaluates `(loop)`
2. The user is in the middle of typing a piece of code that starts with `(loop)`

Issue #1 is hard to solve.
Issuer 2. is related to #308
