### ISSUE TITLE
Ad Block prevents loading Klipse

### ISSUE THREAD

**Issue by polytypic** [viebel/klipse#313]
It seems that Ad Block prevents loading Klipse on at least my library [playground page](https://calmm-js.github.io/partial.lenses/playground.html).  Here is a [problem report](https://gitter.im/calmm-js/chat?at=5b3c3a10bd92d80782919d89) and here is a screenshot:

<img src="https://files.gitter.im/calmm-js/chat/CKRu/image.png"></img>

I wonder what could be done to prevent that issue other than warning against using Ad Block?

Note that I've been using Klipse for a long time already and that was the first time anyone reported the issue.  I suspect most people just think that the library is buggy and never come back.  So, it is possible that this problem has been affecting Klipse for a long time.

**Comment by OvermindDL1** [comment]
How would you propose klipse fixing this as it is not something that is under the control of klipse?  It sounds like the adblock extension being used is just working improperly (I prefer uMatrix myself for the control).

**Comment by rjhilgefort** [comment]
Totally agree! I was just helping diagnose the problem. I just have Ad Block disabled for the domain. I’ll check out uMatrix, thanks!

**Comment by polytypic** [comment]
> @OvermindDL1 How would you propose klipse fixing this as it is not something that is under the control of klipse? 

I haven't analyzed the problem deeply, but it seems that Ad Block prevents loading a specific script that is dynamically loaded by Klipse.  So, one possibility might be to simply change the bundling of Klipse.  For example, instead of separate `javascript.min.js` and `pretty_format.js` scripts, bundling those two scripts together might stop Ad Block from blocking the load.

Note that I'm not suggesting that this is a bug in Klipse per se.

**Comment by viebel** [comment]
Adblock prevents loading Klipse also in my blog at http://blog.klipse.tech/omnibus/2017/04/24/omnibus-1-wallpaper-javascript.html.

I have opened a support ticket at Adblock and requested them to whitelist viebel.github.io.

I hope that they will fix it soon.

**Comment by viebel** [comment]
Klipse script has been whitelisted by AdBlokck.
It should load properly now.
@OvermindDL1  @rjhilgefort @polytypic Can you guys confirm?

**Comment by rjhilgefort** [comment]
Works! Adblock doesn't block anything and I was able to use the REPL. I think this issue can be closed.

![image](https://user-images.githubusercontent.com/2034823/50980813-c8fae500-14b6-11e9-9ae4-f473b276f7c2.png)

**Comment by viebel** [comment]
Excellent! Closing the issue.
Sorry for the inconvenience.
