### ISSUE TITLE
Single Language support

### ISSUE THREAD

**Issue by Immortalin** [viebel/klipse#321]
Is it possible to build for a single language only to optimize space?

**Comment by viebel** [comment]
Hello @Immortalin,
What language are you interested in?
The footprint added to the klipse js file by each unused language is very small. The code that does the code evaluation is loaded dynamically as a separate js file according to the code snippets present on the page.

Therefore, if for instance in your page, you have only `ruby` code snippets, only the ruby evaluator js file will be loaded.


Does it make sense?
