### ISSUE TITLE
(require [re-frame.core]) no longer works in my blog 

### ISSUE THREAD

**Issue by ingesolvoll** [viebel/klipse#322]
http://ingesolvoll.github.io/posts/2017-06-29-re-frame-side-effects-as-data/

Network addresses such as this is blocked by chrome: https://viebel.github.io/cljs-analysis-cache/cache//re_frame_SLASH_core.js

The blog uses the klipse-integration of cryogen, might be up to a year since I started using cryogen and still sticking with the same version of it.

**Comment by ingesolvoll** [comment]
Now for the weird part. Tested in Microsoft edge, and that works. Could it be my chrome cache, or possibly the double slashes interpreted differently?

**Comment by viebel** [comment]
My guess is that some AdBlocker extension blocks this script.
On Chrome, it works fine (by the way, I really liked your blog post!)
![image](https://user-images.githubusercontent.com/955710/45919668-b4f88c80-bea1-11e8-9c60-328984c86079.png)

There is an open issue related to it: https://github.com/viebel/klipse/issues/313

**Comment by ingesolvoll** [comment]
Thanks! You are right, AdBlock is installed on my Chrome and that was the reason.
