### ISSUE TITLE
Prevent listeners from binding multiple times and simulating multiple files

### ISSUE THREAD

**Issue by Folcon** [viebel/klipse#328]
I've created a rough starting point of the roguelike tutorial that I mentioned at clojurex: [https://folcon.github.io/my-little-roguelike/start.html](https://folcon.github.io/my-little-roguelike/start.html)

The code is here:
[https://github.com/Folcon/folcon.github.io/blob/master/my-little-roguelike/start.html](https://github.com/Folcon/folcon.github.io/blob/master/my-little-roguelike/start.html)

It's permanent home is unlikely to remain there, but you did ask me to message you when something was online.

I have two questions:

1. Is there some way to prevent multiple event listeners binding during re-evaluation?
I've been doing an unbind-bind as shown here which I expected to work, so I'm just wondering if it's some klipse specific interaction that I'm not aware of:
```clojure
(.removeEventListener (.-body js/document) "keydown" on-key-press)
(.addEventListener (.-body js/document) "keydown" on-key-press)
```
But it doesn't appear to stop it.

2. I was thinking of ways to extend this tutorial, starting with defining multiple namespaces. I was thinking of simulating multiple namespaces using the editor as by tracking "files" where when the user chooses to swap to another namespace I set the text of the klipse editor. Would that work or is this out of scope of use-cases for klipse?

**Comment by viebel** [comment]
Your roguelike looks cool!

1. There is no klipse specific way to prevent from the code to be re-evaluated. What you can do is to put the code that adds the listener into a separate snippet that will never be modified. Therefore the code will not run again and again.

2. You can try to use namespaces inside Klipse, just like this:
~~~clj
(ns my.rogue-a)
(def x 1)
(ns my.rogue-b)
(def x 1)
~~~

**Comment by viebel** [comment]
What do you mean by "safe to use"?

**Comment by Folcon** [comment]
Oh, basically for the tutorial, I only need to add one keydown event handler.
So I did this:
```clojure
(require '[goog.events :as events])
(events/removeAll (.-body js/document) "keydown")
(events/listen (.-body js/document) "keydown" on-key-press)
```

I couldn't do any listing for event handlers in a consistent way so that I could remove them, but it appears the `goog.events` closure lib tracks the event listeners it registers and is able to remove them even in the reloaded context.

Not that it's specially safe or anything. It just happens to work well for this use-case :)...
