### ISSUE TITLE
Build failure on master, non existent cljs version 1.10.492

### ISSUE THREAD

**Issue by rachitnigam** [viebel/klipse#331]
Hi @viebel,

I've been trying to build the project on master (using either `cljs` or `lein build` or `./scripts/build), but the build keeps failing with: 

```
Error building classpath. Could not find artifact org.clojure:clojurescript:jar:1.10.492 in central (https://repo1.maven.org/maven2/)   
```

It seems the latest cljs version on maven (https://repo.maven.apache.org/maven2/org/clojure/clojurescript/) is 1.10.62 and there is no version 1.10.492.

Seeing `project.clj`, the dependency is commented out, but `deps.edn` refers to the non existent version. Can you verify that this build working for you?

Changing the dependency to `1.10.64` in `deps.edn` fixes the problem for me.

More information:
clj version: 1.9.0
leiningen: latest from AUR repository.

**Comment by viebel** [comment]
Currently, Klipse uses  a version of clojurescript that has not yet been released (1.10.492).
Before launching Klipse, one has to install clojurescript 1.10.492 on its local maven.
This is how we achieve this:
~~~bash
git clone git@github.com:clojure/clojurescript.git
cd clojurescript
change clojurescript version in project.clj file to be `1.10.492`.
./script/build
lein install
~~~

If everything went correctly, you should see clojurescript 1.10.492 in your local maven repo:
~~~
> ls ~/.m2/repository/org/clojure/clojurescript/1.10.492
_remote.repositories       clojurescript-1.10.492.jar clojurescript-1.10.492.pom
~~~
