### ISSUE TITLE
gitbook html css

### ISSUE THREAD

**Issue by HaoLLL** [viebel/klipse#337]
Great work according to the description:
https://read.klipse.tech/a-new-way-of-teaching-html-and-css/
but I still not figure out how to realize the hello-world function in https://read.klipse.tech/a-new-way-of-teaching-html-and-css/  on my gitbook.
Could you give me more instructions?

**Comment by viebel** [comment]
@HaoLLL What issues are you encountering?

**Comment by HaoLLL** [comment]
Thanks, I finally found the class 'lang-render-html'
