### ISSUE TITLE
Programmatically add and remove DOM nodes from KLIPSE

### ISSUE THREAD

**Issue by dmsnell** [viebel/klipse#338]
See #183 
See [Klipsify an arbitrary HTML element](https://github.com/viebel/klipse/wiki/How-to-Klipsify-an-arbitrary-HTML-element)

## Goal

> I want to be able to programmatically add, track, and remove a DOM node from the KLIPSE core from JavaScript

## Motivation

I'm building a WordPress plugin to dynamically create, rearrange, and remove KLIPSE "blocks" in a blog post. This requires me to work around timing issues with KLIPSE's initialization and it also involves lots of additions and removals in the editing context that aren't present in the viewing context of a rendered web page.

 - **Add**: It's easy enough to add new DOM nodes to the KLIPSE editors through the [instructions found on the wiki](https://github.com/viebel/klipse/wiki/How-to-Klipsify-an-arbitrary-HTML-element).

 - **Remove**: Maybe this works already, but when a post author wants to remove the KLIPSE "block" I want to make sure that KLIPSE doesn't retain the DOM reference and continue to process in the background. I will try and confirm if this appears to be the case or not.

 - **Track**: This one is more unclear to me if it's possible or not. Once I create a new KLIPSE block I need to wrap it into a controlled component in the React/WordPress model. That means that I'll need to attach to the editor's instance to manage change events. Please see the following pseudo-code example for illustration.

## Example

 - We're creating a React component that will load and render KLIPSE
 - The code for the block is stored in an attribute, updated with `this.props.setAttributes()` and retrieved as `this.props.attributes.code`
 - The React component may come and go arbitrarily as people switch between different editing modes: for example, switching from the "code" or "HTML" view of the post vs. the visual mode.

```js
class KlipseEditor extends Component {
	editorNode = React.createRef();
	editor = null;

	componentDidMount() {
		ensureKlipseGlobalIsLoaded().then( klipse => {
			this.editor = klipse.plugin.klipsify( this.editorNode.current, … );

			// update our copy of the data if the user changes the code from
			// inside of KLIPSE itself
			this.editor.on( 'change', e => this.props.setAttributes( { code: e.getValue() } );
		} );
	}

	// update the KLIPSE editor if our code changes externally
	componentDidUpdate( prevProps ) {
		if ( this.props.attributes.code !== prevProps.props.attributes.code ) {
			this.editor.setValue( this.props.attributes.code );
		}
	}

	// remove editor instance from KLIPSE since we won't need it anymroe
	componentWillUnmount() {
		klipse.plugin.unklipsify( this.editor );
	}

	render() {
		return <code ref={ this.editorNode }>{ this.props.attributes.code }</code>
	}
}
```

## Random Notes
 - I think it would be helpful to know if we can rely on a reference value to determine if a DOM node is already `klipsify`'d. For instance, I can track my DOM node and say `klipse.plugin.is_klipse( someNode )`. This would help with registration. Better maybe would be being able to register an already-registered node and know that KLIPSE will ignore the double-registration.

 - beyond dynamic addition and removal the controlled data flow is a source of confusion for me here. all I really need to feel happy is a change handler that I can use to update my external datastore then I need a `set` function to make sure that my external updates make it into the KLIPSE editor. I'm pretty sure these already exist by grabbing the CodeMirror instance, but it would be comforting to have more certainty in the docs

**Comment by viebel** [comment]
There is a global variable that contains all the code mirror editors it's called `klipse_editors`.
Please let me know if it fits your needs
