### ISSUE TITLE
Document or change window.klipse_settings.editor_type for SQL

### ISSUE THREAD

**Issue by lechten** [viebel/klipse#346]
When using SQL with klipse (`selector_sql`), result tables for query results are just shown as HTML code. In the source code of [this tutorial](https://blog.klipse.tech/javascript/2016/11/07/best-sql-tutorial.html) I found the following configuration, with which the HTML tables are actually rendered:

```
window.klipse_settings.editor_type = "html";
```

Previously, I used HTML code blocks with klipse (`selector_eval_html`), which work with default settings. Thus, I was surprised that SQL requires an undocumented setting to render HTML results. Could this please be documented or changed? (The `editor_type` applies to all code fragments, which is not ideal if several languages are used.)

**Comment by viebel** [comment]
Hello @lechten !
I am glad to learn that you find SQL snippet useful.
Can you share more details about your user case?


I've just released a new version of Klipse - `7.9.2` - in which SQL Klipse snippets are automatically in html mode.  No need for `window.klipse_settings.editor_type = "html";` any more!

**Comment by lechten** [comment]
Hi @viebel,

many thanks for your work and the new release! 

Klipse is supported in org-reveal and my fork org-re-reveal, which I'm using to create OER presentations with reveal.js based on [Org mode](https://orgmode.org) source documents. I added SQL support in response to an [issue over there](https://gitlab.com/oer/org-re-reveal/issues/23).
