### ISSUE TITLE
How can I upgrade react to version 16.x?

### ISSUE THREAD

**Issue by zhaoyul** [viebel/klipse#348]
Great project, really enjoy using it on my blog.

I want to use MaterialUI, which depends on react 16.

Thanks for any help in advance.

**Comment by viebel** [comment]
1. What is the code snippets language that you want to use?
2. Can you share the url of one of your blog post where you use Klipse?

**Comment by viebel** [comment]
I deployed a new version that upgrades to react 16.
Bounty cancelled
