### ISSUE TITLE
Using Klipse Without CodeMirror and UI DOM only Evaluation Engine

### ISSUE THREAD

**Issue by azizzaeny** [viebel/klipse#352]
How to use klipse in clojurescript mode without displaying and including codemirror editor, just eval some of the string that i put into it.

My solutions is to hide the codemirror dom and pretend that does not exist, but can we make it not evaluating the selector or transforming the selector into codemirror element.?

basically can I get all the functionality of klipse without codemirror on it, ;)

**Comment by viebel** [comment]
Yes you can. Take a look at https://github.com/viebel/klipse-clj  especially in this part of the code: https://github.com/viebel/klipse-clj/blob/master/src/klipse_clj/lang/clojure.cljs#L310-L341
It's not well documented. 
Feel free to reach out if you have questions

**Comment by azizzaeny** [comment]
Thanks, 
My first trial is to clone the repo, make the repl up and try to go to `klipse-clj.lang.clojure` and start the experiment there.

Now  I have another problem.. how can I get the dependencies loaded if I require deps from the classpath. I cannot use `data-external-libs` anymore. can I get the `load-fn` from klipse ?

[Imgur](https://i.imgur.com/okMT445.png)

Another issue is can I host my own analysis cache (`analyzer, compiler, tagged_literal .cljs cljc, `) it seems always trying to load from `https://viebel.github.io` , is there any configuration that can use before trying to use `the-eval` function?

**Comment by viebel** [comment]
As I said `klipse-clj` is not well documented. PR with documentation improvements are more than welcome!
