### ISSUE TITLE
XHR failed loading

### ISSUE THREAD

**Issue by rdbeach** [viebel/klipse#368]
Hi. My plan is to build an interactive version of klipse for my whiteboard:

https://github.com/rdbeach/wb

I tested an html page for clojure snippets. The evaluator seems to work, but in the console I'm getting 4-5 of these types of errors:

```
XHR failed loading: GET
https://viebel.github.io/klipse-clj/target/public/cljs-out/dev/cljs/tagged_literals.cljs.cache.json
```

Any idea what this is about? The files don't even exist, apparently.

You can see for yourself here:

https://lcfprep.com/whiteboard/klipse_clojure.html

Btw, my other test went smoothly.

**Comment by viebel** [comment]
Your whiteboard looks good.
How do you plan to integrate Klipse into it?

Don't worry about the files that Klipse tries to load without success. 

The reason is that Klipse tries many files per namespace *.cls, *.clj, *.cljc.
