### ISSUE TITLE
404 on cache files

### ISSUE THREAD

**Issue by strontian** [viebel/klipse#378]
using the klipse script here: https://storage.googleapis.com/app.klipse.tech/plugin/js/klipse_plugin.js

The following files are showing 404s:

https://viebel.github.io/klipse-clj/target/public/cljs-out/dev/cljs/compiler.cljs.cache.json
https://viebel.github.io/klipse-clj/target/public/cljs-out/dev/cljs/tagged_literals.cljs.cache.json
https://viebel.github.io/klipse-clj/target/public/cljs-out/dev/cljs/analyzer.cljs.cache.json 
https://viebel.github.io/klipse-clj/target/public/cljs-out/dev/cljs/compiler.cljs.cache.json 

Not sure if this is an issue or not, but wanted to let you know.

Thanks!

**Comment by viebel** [comment]
That's not an issue.
Klipse doesn't know a priori where the files are located.
It tries several locations.
