### ISSUE TITLE
new issue with reagent, and loading namespaces?

### ISSUE THREAD

**Issue by postylem** [viebel/klipse#383]
I have been using Klipse for interactive clojure codeboxes on a couple different sites (thank you for making it!). I recently (yesterday) noticed two new issues (which might be related).  I have a simple codebox at the top of every page, which makes a namespace and specifies some dependencies, like

```clojure
(ns my.ns
  (:require [reagent.core :as r] ; for some functions I want to define using reagent
            [clojure.zip :as z] ; etc, from Clojure's Core Library
            ))
 ```

Up until recently, this worked beautifully, and I could define functions in the clojure boxes (which would live in namespace `my.ns`), and use tools from reagent.core as well.

Yesterday I noticed two things were different on both sites that I'm using this on, simultaneously (I hadn't modified anything on the sites, so I think it must be due to some external change (I've also noticed similar problems seem to be happening on other sites, including even [posts on blog.klipse.tech](https://blog.klipse.tech/clojure/2016/06/07/klipse-plugin-tuto.html) and [here](https://folcon.github.io/my-little-roguelike/start.html) and [here](https://tammymakesthings.com/posts/2020-05-06-fibonacci-sequence-in-clojure/)))

1. When the page first loads, it doesn't seem to have loaded the namespace, and all the codeboxes that finish with a function defitition show that the ns is `'cljs.user` instead of `'my.ns`.  The namespace code above gives the error: `load-ns-from-file: cannot fetch https://viebel.github.io/klipse-clj/target/public/cljs-out/dev//cljs/core$macros.cljc.cache.json`.
2. Reagent is no longer available (I get the `No such namespace: reagent.core` error when trying to :require reagent.core).  If I remove reagent.core from the require map, problem 1 remains upon the first load of the page, however, in this case, if I reëvaluate any of the code boxes, they seem to function fine: the namespace is `my.ns`, and I can use things from zip like 'z/node' (but then I can't use reagent, of course).

Has something recently changed in how namespaces and dependencies are loaded?

**Comment by postylem** [comment]
I think it might be due to the CORS issue that was just mentioned in issue #382.
<img width="1354" alt="Screen Shot 2020-09-28 at 14 11 57" src="https://user-images.githubusercontent.com/5202957/94469720-94e8bb80-0194-11eb-8442-172c4d8bb563.png">

**Comment by viebel** [comment]
That is due to the same issue as #382 
Should be fixed now.
