### ISSUE TITLE
Adding class="hidden" is not hiding code snippets

### ISSUE THREAD

**Issue by danny-andrews** [viebel/klipse#384]
I followed the instructions [here](https://book.klipse.tech/interactive_javascript_code_snippets.html#rambda-and-underscore) to add a library, but the code snippet is not hidden in the outputted html.

index.html:
```html
<script src="https://unpkg.com/sprintf-js@1.1.2/dist/sprintf.min.js"></script>
    <script>
      window.klipse_settings = {
        selector_eval_js: '.klipse-eval-js',
      };
    </script>
    <script async src="https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js"></script>
```

my-blog-post.md:
```md
<pre class="hidden"><code class="hidden klipse-eval-js" data-external-libs="https://unpkg.com/sprintf-js@1.1.2/dist/sprintf.min.js">
sprintf
</code></pre>
```

Result:
![image](https://user-images.githubusercontent.com/14965732/99014981-7870ca80-2519-11eb-8128-77c5f512a390.png)

**Comment by viebel** [comment]
You need to add the CSS for the class hidden:

~~~css
.hidden {
    display: none;
}
~~~
