### ISSUE TITLE
Unable to use npm package

### ISSUE THREAD

**Issue by withyellow** [viebel/klipse#385]
package version:

```json
"codemirror": "^5.58.3",
"klipse": "^7.10.5",
```

`import '../../node_modules/klipse/dist/javascript.inc';` 
Throw error:
```
./node_modules/klipse/dist/javascript.inc.js:6:0
Module not found: Can't resolve '../../lib/codemirror'
null
```

`import '../../node_modules/klipse/dist/klipse_plugin';`
Throw error:
```
./node_modules/klipse/dist/klipse_plugin.js:318:0
Module not found: Can't resolve '../../lib/codemirror'
null
```

I want to use this plugin to run `JS` snippets, script tag works well, but I want to use npm package instead, is there some wrong with npm package or I missed something?

**Comment by naboo-sy** [comment]
config.vm.provider "virtualbox" do |v|
    v.customize ["sharedfolder", "add", :id, "--name", "www", "--hostpath", (("//?/" + File.dirname(__FILE__) + "/www").gsub("/","\\"))]
end
config.vm.provision :shell, inline: "mkdir /home/vagrant/www"
config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` > www /home/vagrant/www", run: "always"
