### ISSUE TITLE
Python dependency on skulpt.0.10.0.min.js?

### ISSUE THREAD

**Issue by lechten** [viebel/klipse#397]
In [this commit](https://github.com/viebel/klipse/commit/ae37500bc3ea8458941c112f2869e4f607107ce2) the skulpt dependency was changed to 0.10.0. Is that a hard dependency? Only for Python? (In [docs/misc/skulpt.html](https://github.com/viebel/klipse/blob/master/docs/misc/skulpt.html) I still see `skulpt.min.js` without version.)

I would be happy if I could just use [skulpt-dist](https://github.com/skulpt/skulpt-dist)...

**Comment by viebel** [comment]
I have upgraded skulpt to `0.11.0`
I prefer not to use a location where the content is not immutable as it might break Klipse!

For the sake of curiosity what feature of `0.11.0` do you need?

**Comment by lechten** [comment]
Thank you for your reply! I do not need any specific feature of skulpt, I just include that as dependency for Klipse. I wonder how to do that in a stable way. If you have got a suggestion I'd be happy to read that. Feel free to ignore the remainder...

[My environment](https://gitlab.com/oer/emacs-reveal/) stopped working when I updated Klipse and version numbers appeared in [src/klipse/lang/python.cljs](https://github.com/viebel/klipse/blob/master/src/klipse/lang/python.cljs) because I did not provide that specific version.

Originally, I was not aware that you ship skulpt in [docs/repo/js](https://github.com/viebel/klipse/tree/master/docs/repo/js), which is why I include skulpt-dist (as [Git submodule](https://gitlab.com/oer/klipse-libs), so I'm free to fix any specific commit/version).

Currently, in addition to the submodule I also copy files with version numbers from `docs/repo/js` (which I consider bad style as neither origin nor license are visible - I trust that you use unchanged files). This works but is less than ideal.
