### ISSUE TITLE
(+ 42) does not work

### ISSUE THREAD

**Issue by lgrapenthin** [viebel/klipse#6]

**Comment by viebel** [comment]
Thanks for reporting this issue.

It is a bug on cljs self host code.
I have opened a JIRA issue: http://dev.clojure.org/jira/browse/CLJS-1609

**Comment by viebel** [comment]
The issue has been fixed.
You can check here: http://app.klipse.tech/?cljs_in=(%2B%2042)

**Comment by lgrapenthin** [comment]
@viebel There is no transpiled code on the right hand side.
