### ISSUE TITLE
Ability to pretty-print the generated js

### ISSUE THREAD

**Issue by ducky427** [viebel/klipse#61]
It would be nice if the generated javascript could be pretty printed.

I think it should be possible to do it via [js-beautify](https://github.com/cljsjs/packages/tree/master/js-beautify).

**Comment by viebel** [comment]
Good idea! I'll check it.

**Comment by viebel** [comment]
@ducky427 Issue solved by #106 
Now your [article](http://blog.ducky.io/clojurescript/2016/06/08/more-defprotocol/) looks very nice!

Are you planning to write more articles with interactive code snippets?

**Comment by ducky427** [comment]
thats awesome! 

been bogged down by work too much. So haven't had any free time. Hoping that changes. :)

again, you are doing great work. keep it up!

**Comment by viebel** [comment]
Thanks.
Ping me whe u write another article

**Comment by ducky427** [comment]
will do.

cheers.
