### ISSUE TITLE
Live evaluatino is not working on 2016/05/30/spec.html on chrome

### ISSUE THREAD

**Issue by kimh** [viebel/klipse#71]
Live evaluation is not working when I open http://blog.klipse.tech/clojure/2016/05/30/spec.html.

When evaluating the followings

```
(ns my.spec
  (:require [cljs.spec :as s]))
(ns my.spec
  (:require [cljs.spec :as s]))
```

I got the following error.

```
#error {:message "No such namespace: goog.object, could not locate goog/object.cljs, goog/object.cljc, or Closure namespace \"goog.object\"", :data {:tag :cljs/analysis-error}}
```

I'm getting the same error for all evaluations in the article. Live evaluation seems working on other articles: i.g. http://blog.klipse.tech/clojure/2016/06/07/klipse-plugin-tuto.html

I'm using Chrome 51.0.2704.103 on OSX 10.11.4 (15E65). The page works on Safari.

**Comment by viebel** [comment]
Thanks for reporting

**Comment by viebel** [comment]
Could you try to clean the cache?

**Comment by kimh** [comment]
Clearing cache did work! Sorry for bothering.
