### ISSUE TITLE
Missing: How it Works

### ISSUE THREAD

**Issue by francoislaberge** [viebel/klipse#75]
hi,

I love this kind of tool. I wouldn't want to make websites that depend on services though. It's not clear by the project's description if it uses a backend of some sort. Does it? If so or not, I'd recommended pointing that out as it's a selling point if it's backend free.

Thanks,
Francois

**Comment by viebel** [comment]
@francoislaberge no server at all!
the README has been updated.

Thanks for the report.

**Comment by francoislaberge** [comment]
Awesome, thanks! 

Related: Why wait 2 seconds to run it then? I was assuming to throttle server CPU usage. Sub 100ms would be even better IMHO. Is this a setting?

**Comment by francoislaberge** [comment]
Actually a debounce approach of ~100ms (or some other near instant duration) might be best:
https://css-tricks.com/the-difference-between-throttling-and-debouncing/
