### ISSUE TITLE
Figwheel howto has been removed from README

### ISSUE THREAD

**Issue by daslu** [viebel/klipse#78]
It was useful to have it there, imho.

I mean the line
``` bash
rlwrap lein run -m clojure.main scripts/figwheel.clj
```

**Comment by daslu** [comment]
Also, telling where to go in the browser
(http://localhost:5014/index-dbg.html)
may save a lot of time to newcomers.

**Comment by viebel** [comment]
It has moved here: https://github.com/viebel/klipse/blob/master/contributing.md
